### ISSUE TITLE
`pluck` should work like in ActiveRecord

### ISSUE THREAD

**Issue by rferg** [Beyond-Finance/active_force#27]
I want an array of single column values from a query. If I run the following:

```ruby
Af::CampaignSource.all.pluck(:id)
```

It generates SOQL that still includes all of the columns in the `SELECT` clause:

```sql
SELECT Id, Alfred_Affiliate_Id__c, CreatedById, CreatedDate, IsDeleted, LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate, Name, OwnerId, Status__c, SystemModstamp, Type__c FROM Campaign_source__c
```

Also, it appears to still be instantiating ActiveModels for each record.

To get the more efficient query with only the columns I need, I have to use `select`:

```ruby
Af::CampaignSource.select(:id)
```

```sql
SELECT Id FROM Campaign_source__c
```

However, this returns a collection of ActiveModels with only the given field populated.  I have to then call `pluck(:id)` on that to get my array of ids.

It would be best if `Af::CampaignSource.pluck(:id)` executed a query selecting only the requested columns and returned an array containing only those values, instead of going through the intermediate ActiveModel objects.

Calling `.pluck(:id, :status)` with multiple arguments should return an array of arrays with the values in the same order as the given columns.

**Comment by Aaryanpal** [comment]
Assign to me @rferg
