### ISSUE TITLE
Enable "wildcard" functionality for field lists.

### ISSUE THREAD

**Issue by JeffLuckett** [Beyond-Finance/active_force#35]
**Is your feature request related to a problem? Please describe.**
Most RDMS allow for "Select * from ..." functionality.  However, AF currently relies on explicit field lists.

SOQL does provide `fields(all/custom/standard)` functionality, which may provide some relief from the brittleness of the models being so closely tied to the schema due to the requirement that all fields be defined, and included in all `select` requests.

**Describe the solution you'd like**
Implement using the `fields(<field_type>)` method in SELECT queries as documented here: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_fields.htm

**Describe alternatives you've considered**
Hating your life because schema changes blow up your code.

**Additional context**

**Comment by rferg** [comment]
@JeffLuckett As I was working on this, I found that `FIELDS(ALL)` and `FIELD(CUSTOM)` are only supported in the standard REST API with queries that `LIMIT` by <= 200 (see [here](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_fields.htm#bounded_and_unbounded_queries)).

I tested with `SELECT FIELDS(ALL) FROM Account` and indeed it returns: `MALFORMED_QUERY: The SOQL FIELDS function must have a LIMIT of at most 200`.

I'm not sure if this is worth adding unless we want to write paging logic for every query that isn't explicitly limited for < 200.

**Comment by JeffLuckett** [comment]
@rferg - boo hiss.

**Comment by JeffLuckett** [comment]
I guess we should close this one then.

**Comment by rferg** [comment]
> I guess we should close this one then.

Salesforce claims another victim.

**Comment by JeffLuckett** [comment]
Not practical due to SF RestAPI limitations.
