### ISSUE TITLE
Implement the scoped_as functionality for has_one relations

### ISSUE THREAD

**Issue by josemarialopez** [Beyond-Finance/active_force#48]
### Description

Sometimes we are in a situation where we would like to create a `has_one` association for an ActiveForce model, but we would like to define the scope to "pick" the desired record. This functionality is available at the moment for `has_many` relations, but it's completely ignored for `has_one` ones. It would be desirable to have this option to solve for example the following situation:

```
class Af::Opportunity
  has_one :bank_account, model: 'Af::BankAccount', scoped_as: { where(...).order('CreatedDate DESC') }
end
```

### Acceptance Criteria
* We have implemented the scoped_as functionality for has_one relations.

**Comment by rferg** [comment]
This should be pretty easy.  I'll see if I can get a PR up today.
